# Generated by Django 3.2.5 on 2022-01-23 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='title_tag',
            field=models.CharField(default='TheLine', max_length=15),
        ),
    ]
